cat <<EOF>> resource-quota.yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: dev
spec:
  hard:
    pods: "10"
    requests.cpu: "1"
    requests.memory: 5Gi
    limits.cpu: "2"
    limits.memory: 10Gi
EOF

kubectl get quota --namespace=dev
kubectl delete quota compute-quota