FROM Ubuntu
CMD sleep 5

docker build -t ubuntu-sleeper

FROM Ubuntu
ENTRYPOINT ["sleep"]
CMD ["5"]

apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
 containers:
 - name: ubuntu-sleeper
   image: ubuntu-sleeper
   command: ["sleep"]
   args: ["10"]

# cat /etc/kubernetes/manifests/kube-apiserver.yaml