apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
spec:
 containers:
 - name: simple-webapp-color
   image: nginx
   ports:
   - containerPort: 8080
   envFrom:
   - configMapRef:
       name: app-config



/*
env:
- name: APP_COLOR
	valueFrom:
		configMapRefKey:
			name: app-config
			key: APP_COLOR

*/