apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: sahdev
spec:
  signerName: kubernetes.io/kube-apisever-client
  groups:
  - system:authenticated
  usages:
  - digital signature
  - key encipherment
  - client auth
  request:
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0djMkZvWkdWMk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQTUvQ0xFYTJBRnF2RjczVnJ3WVd2UmpGSkN2RkM0RDB0VjZnMzF3N1ZXNnhxCnRCN2lrbFNvQ1g4bEIra0NuQ3dtdTlhZXUySWdNSjBwc3NGaisvbDY1bi9kaDhneEtLd1RiNThMQVJLcVZOd3IKZDJXVEhxcjA0NVdHT0ltZlZLWHl3K2pZNFBaL2JydVdOS3NVSXBEQmNuTENwQTRYekFjUSsxSld2Z1BWaTVXSgpHeFYzUEVkMHlMbzFVRkFzYlZtZUZPWGdyNFdIaU5LV2xrRkRrN2pxSUh3T0ZwZ05vdHlBbzA5Mk9lV3Z6RzJLCnNjRGZETWhOL2ROR25oVGd3WVhRQkllWDVUUTBHM2t0dmRaNHo3RnJnNmVLZTZ1N1FEZVlhQXg0ZDRlYWVPWFAKZlBCOVZRSC9kYU5obVdHMVdWK0RLVG5UdnhlaEVyaHRRb2VUTjl2N0NRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBQzExREZEL3FocjQ3VVJPNmRUR1pPcHNSQUh0cnNob0lKTGFsVDViOEFSaDRubThWTkVEClY0ODFQWHVicWhuUVNIaHRPV3BGK0M0WTlGQjJsa1hycGFHTWJ1Vks0NWpqYTN4dzc1aGl3UXBXSUVLZ2Q4UFQKMy9uOGxCNE9Tc09MM0RuTWZlMXV3QWZvK3c2K0xXY0pDNnUyb3cwQ3piWWtzNXJyenVGRU04Nmo1YVhuZkp4ZQoxQUJxRzl2dHhQeklDRjM2bG1PZ2g2cHU0WXB5ZlYzSVNUblNTQWNHWm8wN2szZ0xFOWE3eDVMNEYrcG9mVmtoCmFmVGEvRnM1OGFnWHhMbXNlL0tickJFQ3hERE9keFhlWk9xVFRhN1pxb3F1UjFuc1pCVFhIQm9XeU9pT051S3gKT29GUzE0aFJ6UzBzbEE3bXlQZ0lMNHdXb2kyK0xNeGxGQXc9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=

  sudo openssl genrsa -out sahdev.key 2048
  sudo openssl req -new -key sahdev.key -subj "/CN=sahdev" -out sahdev.csr
  cat sahdev.csr | base64 | tr -d "\n"
  kubectl get csr
  kubectl certificate approve sahdev
  kubectl get csr sahdev -o
